version: '3.8'

networks:
  ayuntamiento-net:

services:

  mongo:
    image: mongo:6
    container_name: ayuntamiento-mongo
    restart: always
    ports:
      - "27020:27017"
    networks:
      - ayuntamiento-net

  ayuntamiento-access:
    build:
      context: .
    container_name: ayuntamiento-access
    ports:
      - "8094:8094"
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - ayuntamiento-net
    environment:
      SERVER_PORT: 8094
      SPRING_DATA_MONGODB_URI: mongodb://ayuntamiento-mongo:27017/ayuntamiento-db
       # Config Server
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      # Eureka (host local, fuera del contenedor)
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka
