version: '3.8'

networks:
  ayuntamiento-net:

services:

  mongo:
    image: mongo:6
    container_name: ayuntamiento-mongo
    restart: always
    ports:
      - "27020:27017"
    networks:
      - ayuntamiento-net

  ayuntamiento-access:
    build:
      context: .
    container_name: ayuntamiento-access
    ports:
      - "8094:8094"
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - ayuntamiento-net
