version: '3.8'

networks:
  pollution-net:

services:

  mysql:
    image: mysql:8
    container_name: pollution-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollutiondb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    networks:
      - pollution-net

  mongo:
    image: mongo:6
    container_name: pollution-mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - pollution-net
