version: '3.8'

networks:
  pollution-net:

services:

  mysql:
    image: mysql:8
    container_name: pollution-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollutiondb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    networks:
      - pollution-net

  mongo:
    image: mongo:6
    container_name: pollution-mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - pollution-net

  pollution-access:
    build:
      context: .
    container_name: pollution-access
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - mongo
    restart: on-failure
    networks:
      - pollution-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pollution-mysql:3306/pollutiondb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: always
      SPRING_DATA_MONGODB_URI: mongodb://pollution-mongo:27017/pollution-db
      SERVER_PORT: 8086
      SPRING_CLOUD_CONFIG_ENABLED: false
