version: '3.8'

networks:
  bike-net:

services:
  mysql:
    image: mysql:8
    container_name: bike-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bikedb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    networks:
      - bike-net

  mongo:
    image: mongo:6
    container_name: bike-mongo
    restart: always
    ports:
      - "27019:27017"
    networks:
      - bike-net

  bike-access:
    build:
      context: .
    container_name: bike-access
    ports:
      - "8091:8091"
    depends_on:
      - mysql
      - mongo
    restart: on-failure
    networks:
      - bike-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bike-mysql:3306/bikedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: always
      SPRING_DATA_MONGODB_URI: mongodb://bike-mongo:27017/bikes-status
      SERVER_PORT: 8091
